### ISSUE TITLE
Download from KDE store is broken

### ISSUE THREAD

**Issue by Martan404** [kraken-afk/archsimpleblue#1]
When trying to download the new archsimpleblue-kde6 release from the KDE store it throws an error saying
`Cannot install 'Arch Simple Blue KDE 6' because it points to a web page. Click [here](https://files04.pling.com/api/files/download/j/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE3MTAxMDQyMjAiLCJvIjoiMSIsInMiOiIwM2EzZWNjOTU4YWE4MDY4ZThiNDc3NzNhNDBlYTBiNGYxNDA1YThkNTk4Mzg3ZWM5NWYyZmMzZWFlZGE5MGEwMGE0NWE5MWFhODUyNzNiZGJlZjgyMDkzZjk5NTEwNjYxOWYzYTcxZDAzZWJmZWY0MjZmYjQ0YjZiZmNkYmY1MyIsInQiOjE3MTAyMjMxMDgsInN0ZnAiOm51bGwsInN0aXAiOiIyMTcuMjA5LjcuMTU3In0.tta4IXmsu8rJ2aE3Ddrt9KWH37fH-2hvxSCi7riycFk/archsimpleblue-kde6) to finish the installation.`
then it takes me here to this github page

**Comment by kraken-afk** [comment]
Hi, sorry if the download option make you confused, you can download it from this github, and extract it to `~/.local/share/plasma/look-and-feel`

![Desktop 1_065](https://github.com/kraken-afk/archsimpleblue-kde6/assets/77183252/b1dc2c3f-df2e-4f43-9eb8-f44633e2c56f)

Or, you can download the tar version. extract it and you're ready to go.

![Desktop 1_066](https://github.com/kraken-afk/archsimpleblue-kde6/assets/77183252/c05c8b87-be56-44bf-ab08-8c216759a51c)

**Comment by Martan404** [comment]
Sorry. I was trying to install it from the System Settings and that is what throws me the error.

But on the KDE store page it states that


```
Installation
You can install it via System Settings or go to https://github.com/kraken-afk/archsimpleblue
Extract it to ~/.local/share/plasma/look-and-feel/
```

Edit: I tried installing manually two times but when I do the preview inside the settings app it just show me the default breeze logo and when I boot my computer it shows the breeze logo.

**Comment by kraken-afk** [comment]
try rename the folder from `archsimpleblue-kde6` to `archsimpleblue`, it should be fine. i just update the file realize about the issue while ago, and immediately update the source folder name. tell me if there's more issue

**Comment by kraken-afk** [comment]
try rename the folder from `archsimpleblue-kde6` to `archsimpleblue`, it should be fine. i just realize about the issue while ago, and immediately update the source folder name. tell me if there's another issue.

**Comment by Martan404** [comment]
Installing in System Settings work now! It also displays the splash screen correctly. Thanks!
However, when downloading the zip from github the folder gets named `archsimpleblue-main`. I think that it's worth mentioning in the manual installation notes that the folder should be renamed to `archsimpleblue-main`.
